stages:
  - compose-test
  - lint
  - test
  - build
  
variables:
  PYTHONPATH: "$CI_PROJECT_DIR/fastapi-service/app"

lint:
  stage: lint
  image: python:3.11
  script:
    - pip install ruff
    - ruff check fastapi-service/app

test:
  stage: test
  image: python:3.11
  variables:
    PYTHONPATH: fastapi-service
  script:
    - pip install -r fastapi-service/requirements.txt
    - pytest fastapi-service/app/tests
  rules:
    - changes:
        - fastapi-service/**

build:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  script:
    - docker build -t weather-backend ./fastapi-service
    - docker build -t weather-frontend ./frontend
    - docker build -t weather-airflow ./airflow

compose-test:
  stage: compose-test
  image: docker:latest
  services:
    - docker:dind
  variables:
    DOCKER_HOST: tcp://docker:2375
    DOCKER_TLS_CERTDIR: ""
  script:
    - apk add --no-cache curl
    - docker compose version
    - docker compose -f docker-compose.yml up -d --build
    - sleep 15  # gib den Containern Zeit zum Starten
    - docker compose ps
    - docker compose logs backend
    - docker exec fastapi-backend wget --spider -q http://localhost:8000/health || (echo "❌ Backend nicht erreichbar!" && exit 1)
    - docker compose down