services:
  db:
    image: postgres:15
    container_name: postgres-db
    environment:
      POSTGRES_USER: weather
      POSTGRES_PASSWORD: weather123
      POSTGRES_DB: weatherdb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U weather -d weatherdb || exit 1"]
      interval: 5s
      timeout: 5s
      retries: 20
      start_period: 10s

  backend:
    build: ./fastapi-service
    container_name: fastapi-backend
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DATABASE_URL=postgresql://weather:weather123@db:5432/weatherdb
    working_dir: /fastapi-service
    # Siehe Schritt 2 unten: Wait-Loop + create_db + uvicorn
    command: >
      bash -lc '
      until pg_isready -h db -p 5432 -U weather -d weatherdb; do
        echo "waiting for db..." && sleep 2
      done;
      python -m app.create_db && uvicorn app.main:app --host 0.0.0.0 --port 8000'
    #ports:
    #  - "8000:8000"
    volumes:
      - ./fastapi-service:/fastapi-service

  airflow-db:
    image: postgres:15
    container_name: airflow-db
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    volumes:
      - airflow_postgres_data:/var/lib/postgresql/data

  airflow-scheduler:
    build:
      context: .
      dockerfile: airflow/Dockerfile
    container_name: airflow-scheduler
    restart: always
    depends_on:
      - airflow-db
    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@airflow-db:5432/airflow
      - AIRFLOW__WEBSERVER__SECRET_KEY=mysupersecret
      - PYTHONPATH=/opt/shared-code
    command: scheduler
    #volumes:
      #- ./airflow/dags:/opt/airflow/dags
      #- ./fastapi-service/app:/opt/shared-code/app


  airflow-webserver:
    build:
      context: .
      dockerfile: airflow/Dockerfile
    container_name: airflow-webserver
    restart: always
    depends_on:
      - airflow-scheduler
    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@airflow-db:5432/airflow
      - AIRFLOW__WEBSERVER__SECRET_KEY=mysupersecret
      - PYTHONPATH=/opt/shared-code
    command: webserver
    #ports:
    #  - "8080:8080"
    #volumes:
      #- ./airflow/dags:/opt/airflow/dags
      #- ./fastapi-service/app:/opt/shared-code/app

  frontend:
    build: ./frontend
    container_name: weather-frontend
    #ports:
    #  - "3000:3000"
    depends_on:
      - backend
    volumes:
      - ./frontend:/app

  caddy:
    image: caddy:2.7
    container_name: caddy
    restart: unless-stopped
    ports:
      - "80:80"      # HTTP (für ACME + Redirect)
      - "443:443"    # HTTPS (öffentlich)
    volumes:
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy_data:/data
      - caddy_config:/config
    env_file:
      - .env
    depends_on:
      - frontend
      - backend
      - airflow-webserver  

volumes:
  postgres_data:
  airflow_postgres_data:
  caddy_data:
  caddy_config: