version: "3.9"

services:
  db:
    image: postgres:15
    container_name: postgres-db
    environment:
      POSTGRES_USER: weather
      POSTGRES_PASSWORD: weather123
      POSTGRES_DB: weatherdb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: ./fastapi-service
    container_name: fastapi-backend
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://weather:weather123@db:5432/weatherdb
    ports:
      - "8000:8000"
    volumes:
      - ./fastapi-service:/fastapi-service

volumes:
  postgres_data: